### ISSUE TITLE
REST api wrapper

### ISSUE THREAD

**Issue by petergombos** [ARandomInvestor/amfeix-tools#1]
Hey man, awesome work to dig out this data! :)

I'm thinking of building an automated email system for investors where they can subscribe with their investor address and receive daily update on ROI and current balance. It would be super cool if you could build a rest api wrapper for your scripts so I could spin it up in a docker container and build the app other parts in node.js/javascript.

Would you be up for it?

Cheers

**Comment by ARandomInvestor** [comment]
Seems like you got it all sorted out now :)
